services:
  # JAC Server (Backend)
  jac-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: jac-gpt-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./server:/app
      - jac_server_data:/app/data
      - jac_server_logs:/app/logs
    networks:
      - jac-gpt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend (Webapp)
  jac-webapp:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
        - VITE_JAC_USER_EMAIL=test@mail.com
        - VITE_JAC_USER_PASSWORD=password
    container_name: jac-gpt-webapp
    restart: unless-stopped
    ports:
      - "3000:80"  # Use port 3000 to avoid conflict with system nginx
    depends_on:
      - jac-server
    networks:
      - jac-gpt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  jac_server_data:
    driver: local
  jac_server_logs:
    driver: local

networks:
  jac-gpt-network:
    driver: bridge
    name: jac-gpt-network
